# Generated by Django 2.1.8 on 2019-10-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar/%Y%m%d/', verbose_name='头像'),
        ),
    ]
