# Generated by Django 2.1.8 on 2019-09-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time'], 'verbose_name': '我的博客', 'verbose_name_plural': '我的博客'},
        ),
    ]
