# Generated by Django 2.1.8 on 2019-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190905_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-create_time', 'title'], 'verbose_name': '我的博客', 'verbose_name_plural': '我的博客'},
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
