# Generated by Django 2.1.8 on 2019-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190908_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='文章摘要'),
        ),
    ]
