# Generated by Django 2.1.8 on 2019-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190908_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, default='No Value', max_length=200, verbose_name='文章摘要'),
        ),
    ]
